export type AvailableCountryCovidTableFields = 
| 'hospPatients'
| 'icuPatients'
| 'newCases'
| 'newDeaths'
| 'newTests'
| 'newVaccinations'
| 'peopleFullyVaccinated'
| 'peopleVaccinated'
| 'positiveRate'
| 'testsPerCase'
| 'totalBoosters'
| 'totalCases'
| 'totalDeaths'
| 'totalTests'
| 'totalVaccinations'
| 'weeklyHospAdmissions'
| 'weeklyIcuAdmissions'

export const setWithAllCountryCovidTableFields = new Set<AvailableCountryCovidTableFields>([
  'hospPatients'
,'icuPatients'
,'newCases'
,'newDeaths'
,'newTests'
,'newVaccinations'
,'peopleFullyVaccinated'
,'peopleVaccinated'
,'positiveRate'
,'testsPerCase'
,'totalBoosters'
,'totalCases'
,'totalDeaths'
,'totalTests'
,'totalVaccinations'
,'weeklyHospAdmissions'
,'weeklyIcuAdmissions'
])