query countryCovidTableData($countryCovidDataInput: CountryCovidDataInput!, 
$shouldIncludeHospPatients: Boolean!
$shouldIncludeIcuPatients: Boolean!
$shouldIncludeNewCases: Boolean!
$shouldIncludeNewDeaths: Boolean!
$shouldIncludeNewTests: Boolean!
$shouldIncludeNewVaccinations: Boolean!
$shouldIncludePeopleFullyVaccinated: Boolean!
$shouldIncludePeopleVaccinated: Boolean!
$shouldIncludePositiveRate: Boolean!
$shouldIncludeTestsPerCase: Boolean!
$shouldIncludeTotalBoosters: Boolean!
$shouldIncludeTotalCases: Boolean!
$shouldIncludeTotalDeaths: Boolean!
$shouldIncludeTotalTests: Boolean!
$shouldIncludeTotalVaccinations: Boolean!
$shouldIncludeWeeklyHospAdmissions: Boolean!
$shouldIncludeWeeklyIcuAdmissions: Boolean!
) {
  countryCovidTableData(countryCovidDataInput: $countryCovidDataInput) {
    id
    name
    date
    isoCode
    hospPatients @include(if: $shouldIncludeHospPatients)
    icuPatients @include(if: $shouldIncludeIcuPatients)
    newCases @include(if: $shouldIncludeNewCases)
    newDeaths @include(if: $shouldIncludeNewDeaths)
    newTests @include(if: $shouldIncludeNewTests)
    newVaccinations @include(if: $shouldIncludeNewVaccinations)
    peopleFullyVaccinated @include(if: $shouldIncludePeopleFullyVaccinated)
    peopleVaccinated @include(if: $shouldIncludePeopleVaccinated)
    positiveRate @include(if: $shouldIncludePositiveRate)
    testsPerCase @include(if: $shouldIncludeTestsPerCase)
    totalBoosters @include(if: $shouldIncludeTotalBoosters)
    totalCases @include(if: $shouldIncludeTotalCases)
    totalDeaths @include(if: $shouldIncludeTotalDeaths)
    totalTests @include(if: $shouldIncludeTotalTests)
    totalVaccinations @include(if: $shouldIncludeTotalVaccinations)
    weeklyHospAdmissions @include(if: $shouldIncludeWeeklyHospAdmissions)
    weeklyIcuAdmissions @include(if: $shouldIncludeWeeklyIcuAdmissions)
  }
}
