query countryCovidData($countryCovidDataInput: CountryCovidDataInput!) {
  countryCovidData(countryCovidDataInput: $countryCovidDataInput) {
    id
    name
    isoCode
    covidCases {
      date
      newCases
    }
  }
}
